// ===================== DISTRITOS Y LOCALIDADES BA =====================
const Map<String, List<String>> kDistritosBA = {
  'Almirante Brown': ['Adrogué','Burzaco','Claypole','Don Orione','Glew','José Mármol','Longchamps','Malvinas Argentinas','Ministro Rivadavia','Rafael Calzada','San Francisco de Asís','San José'],
  'Avellaneda': ['Avellaneda','Crucecita','Dock Sud','Gerli','Piñeiro','Sarandí','Villa Domínico'],
  'Azul': ['Azul','Cacharí','Chillar','16 de Julio'],
  'Bahía Blanca': ['Bahía Blanca','Cabildo','Cerri','General Daniel Cerri','Ingeniero White','Loma Paraguaya','Villa Bordeau'],
  'Balcarce': ['Balcarce','Los Pinos','Napaleofu','Ramos Otero','San Agustín'],
  'Baradero': ['Baradero','Ireneo Portela','Portela','Santa Coloma'],
  'Benito Juárez': ['Benito Juárez','Barker','López','Tedín Uriburu'],
  'Berazategui': ['Berazategui','Bosques','El Pato','Guillermo Enrique Hudson','Juan María Gutiérrez','Pereyra','Plátanos','Ranelagh','Villa España'],
  'Bolívar': ['Bolívar','Hinojo','Pirovano','Urdampilleta'],
  'Bragado': ['Bragado','Comodoro Py','La Limpia','O Brien','Olascoaga','Mechita'],
  'Brandsen': ['Brandsen','Gorchs','Jeppener','La Bodega','Oliden'],
  'Campana': ['Campana','Ing. Leandro N. Alem','Otamendi'],
  'Cañuelas': ['Cañuelas','Máximo Paz','Santa Rosa'],
  'Capitán Sarmiento': ['Capitán Sarmiento','El Arbolito','Franklin'],
  'Carlos Casares': ['Carlos Casares','Colonia Mauricio','Hortensia','La Sofía','Mauricio'],
  'Carlos Tejedor': ['Carlos Tejedor','Colonia Seré','Curaru','Moctezuma','Timote'],
  'Carmen de Areco': ['Carmen de Areco','Cañada Seca','Parada Robles'],
  'Castelli': ['Castelli','La Luisa'],
  'Chacabuco': ['Chacabuco','La Invencible','O Higgins','Rafael Obligado'],
  'Chascomús': ['Chascomús','Adela','Gándara','General Paz','Lezama'],
  'Chivilcoy': ['Chivilcoy','Emilio Ayarza','La Rica','Moquehuá','Ramón Biaus'],
  'Colón': ['Colón','Pearson','Villa Moll'],
  'Coronel Dorrego': ['Coronel Dorrego','Oriente','San Román'],
  'Coronel Pringles': ['Coronel Pringles','Indio Rico','Lartigau'],
  'Coronel Rosales': ['Punta Alta','Bajo Hondo','Caleta Cordova'],
  'Coronel Suárez': ['Coronel Suárez','Cura Malal','D Orbigny','Huanguelen','Mayor Buratovich','San José'],
  'Daireaux': ['Daireaux','Blaquier','Casbas','La Campiña'],
  'Dolores': ['Dolores','Sevigny','Verónica'],
  'Ensenada': ['Ensenada','Punta Lara'],
  'Escobar': ['Escobar','Belén de Escobar','Garín','Ingeniero Maschwitz','Maquinista Savio','Matheu','Open Door'],
  'Esteban Echeverría': ['El Jagüel','La Unión','Luis Guillón','Monte Grande','San José'],
  'Exaltación de la Cruz': ['Capilla del Señor','Los Cardales','Parada Robles','Suipacha'],
  'Ezeiza': ['Carlos Spegazzini','Ezeiza','La Unión','Tristán Suárez'],
  'Florencio Varela': ['Florencio Varela','Ingeniero Juan Allan','Los Hornos','Gobernador Costa','Villa Brown'],
  'Florentino Ameghino': ['Florentino Ameghino','Smith'],
  'General Alvarado': ['Miramar','Mar del Sud','Mechongué'],
  'General Alvear': ['General Alvear','Polvaredas'],
  'General Arenales': ['General Arenales','Ascensión','Ariel','Fontezuela'],
  'General Belgrano': ['General Belgrano','Gorchs','Roque Pérez'],
  'General Guido': ['General Guido','Labardén'],
  'General Juan Madariaga': ['General Juan Madariaga','Costa del Este','Mar de Cobo'],
  'General La Madrid': ['General La Madrid','Aldecoa','El Divisorio'],
  'General Las Heras': ['General Las Heras','González Moreno','Plomer'],
  'General Lavalle': ['General Lavalle','Pavón'],
  'General Paz': ['Ranchos','Villanueva'],
  'General Pinto': ['General Pinto','Germania','Moras','Villa Francia'],
  'General Pueyrredón': ['Mar del Plata','Batán','Sierra de los Padres'],
  'General Rodríguez': ['General Rodríguez'],
  'General San Martín': ['Billinghurst','General San Martín','José León Suárez','Villa Ballester','Villa Lynch','Villa Maipú','Villa Raffo'],
  'General Sarmiento': ['Los Polvorines','Bella Vista','Grand Bourg','José C. Paz','Malvinas Argentinas','Muñiz','Tortuguitas'],
  'General Viamonte': ['Los Toldos','Bunge','Garre','Moctezuma','Zavalía'],
  'General Villegas': ['General Villegas','Banderaló','Carlos Salas','Coronel Charlone','Dos Algarrobos','Mayor Enrique Krausse','Piedritas'],
  'Guaminí': ['Guaminí','Álvaro Barros','Casbas','Laguna Alsina'],
  'Hipólito Yrigoyen': ['Henderson','Casbas','Pedernales'],
  'Hurlingham': ['Hurlingham','Villa Tesei','Villa Luzuriaga','El Palomar'],
  'Ituzaingó': ['Ituzaingó','Haedo'],
  'José C. Paz': ['José C. Paz'],
  'Junín': ['Junín','Agustina','Fortín Tiburcio','Morse','Roberts'],
  'La Costa': ['San Clemente del Tuyú','Las Toninas','Santa Teresita','Mar del Tuyú','Costa del Este','Aguas Verdes','La Lucila del Mar','San Bernardo','Mar de Ajó','Nueva Atlantis'],
  'La Matanza': ['San Justo','Ramos Mejía','González Catán','Laferrère','Lomas del Mirador','Tapiales','Isidro Casanova','Ciudad Evita','Aldo Bonzi'],
  'La Plata': ['La Plata','Abasto','Arturo Seguí','City Bell','El Peligro','Gorina','Hernández','Joaquín Gorina','Los Hornos','Melchor Romero','Olmos','Ringuelet','Romero','Tolosa'],
  'Lanús': ['Lanús','Gerli','Monte Chingolo','Remedios de Escalada','Valentín Alsina'],
  'Laprida': ['Laprida','Pueblo Nuevo'],
  'Las Flores': ['Las Flores','Álvarez de Toledo'],
  'Leandro N. Alem': ['Leandro N. Alem','Alberdi','Arribeños','Carabelas','La Pinta'],
  'Lincoln': ['Lincoln','Arenaza','Bermúdez','Carlos María Naón','El Triunfo','Pasteur','Roberts'],
  'Lobería': ['Lobería','Arenas Verdes','Tamangueyu'],
  'Lobos': ['Lobos','Elvira','La Paz','Lucila','Zapiola'],
  'Lomas de Zamora': ['Lomas de Zamora','Banfield','Temperley','Turdera','Villa Centenario','Villa Fiorito'],
  'Luján': ['Luján','Carlos Keen','Cortínez','Jáuregui','Open Door','Torres'],
  'Magdalena': ['Magdalena','Atalaya','Bartolomé Bavio','General Mansilla','Vergara'],
  'Maipú': ['Maipú','Ayacucho','Coronel Vidal','Las Armas'],
  'Malvinas Argentinas': ['Los Polvorines','Grand Bourg','Ing. Adolfo Sourdeaux','Tortuguitas','Villa de Mayo'],
  'Mar Chiquita': ['Mar Chiquita','Camet','La Caleta','Mechongué','Santa Clara del Mar'],
  'Marcos Paz': ['Marcos Paz'],
  'Mercedes': ['Mercedes','Gowland','Gándara'],
  'Merlo': ['Merlo','Libertad','Mariano Acosta','Pontevedra','San Antonio de Padua'],
  'Monte': ['Monte','Alejandro Korn'],
  'Monte Hermoso': ['Monte Hermoso'],
  'Moreno': ['Moreno','Cuartel V','Francisco Álvarez','La Reja','Trujui'],
  'Morón': ['Morón','El Palomar','Castelar','Haedo'],
  'Navarro': ['Navarro'],
  'Necochea': ['Necochea','Quequén','Nicanor Olivera'],
  'Nueve de Julio': ['Nueve de Julio','Alfredo Demarchi','Carlos Salas','La Niña','Patricios','Quiroga','Ramón Biaus','Sheridan'],
  'Olavarría': ['Olavarría','Espigas','Hinojo','Loma Negra','Recalde','Sierra Chica'],
  'Patagones': ['Carmen de Patagones','Stroeder','Villalonga'],
  'Pehuajó': ['Pehuajó','Colonia Barón','Francisco Madero','Mones Cazón','Nueva Plata'],
  'Pellegrini': ['Pellegrini','Urdampilleta'],
  'Pergamino': ['Pergamino','Acevedo','Fontezuela','Guerrico','Rancagua','Urquiza'],
  'Pila': ['Pila'],
  'Pilar': ['Pilar','Del Viso','Fátima','Manzanares','Manuel Alberti','Presidente Derqui','Zelaya'],
  'Pinamar': ['Pinamar','Cariló','Ostende','Valeria del Mar'],
  'Presidente Perón': ['Guernica','Alejandro Korn'],
  'Puán': ['Puán','Bordenave','Darregueira','Felipe Solá','Pigüé'],
  'Punta Indio': ['Verónica','Pipinas','Álvarez Jonte'],
  'Quilmes': ['Quilmes','Bernal','Don Bosco','Ezpeleta','La Florida','San Francisco Solano','Villa La Florida'],
  'Ramallo': ['Ramallo','Villa Ramallo'],
  'Rauch': ['Rauch','Egaña'],
  'Rivadavia': ['América','Sansinena','Fortín Olavarría'],
  'Rojas': ['Rojas','Carabelas','Los Indios','Vuelta de Obligado'],
  'Roque Pérez': ['Roque Pérez','Cazón'],
  'Saavedra': ['Pigüé','Espartillar','Goyena','Lartigau','Dufaur'],
  'Saladillo': ['Saladillo','Alvear','Del Carril','Polvaredas'],
  'Salliqueló': ['Salliqueló','Quenumá'],
  'Salto': ['Salto','Arrecifes','Buen Retiro','Inés Indart'],
  'San Andrés de Giles': ['San Andrés de Giles','Azcuénaga','Cucullú','Giles','Franklin','Villanueva'],
  'San Antonio de Areco': ['San Antonio de Areco','Duggan','Villa Lía'],
  'San Cayetano': ['San Cayetano','Ochandio','Orense'],
  'San Fernando': ['San Fernando','Virreyes','Victoria'],
  'San Isidro': ['San Isidro','Acassuso','Beccar','La Lucila','Martínez','Rincón de Milberg','Talar de Pacheco'],
  'San Miguel': ['San Miguel','Campo de Mayo','Muñiz','Santa María'],
  'San Nicolás': ['San Nicolás de los Arroyos','Conesa','General Lagos','Ramallo'],
  'San Pedro': ['San Pedro','Gobernador Castro','Lima','Obligado','Río Tala'],
  'San Vicente': ['San Vicente','Alejandro Korn','Domselaar'],
  'Suipacha': ['Suipacha'],
  'Tandil': ['Tandil','Gardey','Los Aromos','María Ignacia-Vela'],
  'Tapalqué': ['Tapalqué','Crotto','Velloso'],
  'Tigre': ['Tigre','Don Torcuato','El Talar','General Pacheco','Dique Luján','La Lonja','Nordelta','Rincón de Milberg','Ricardo Rojas','Villa la Ñata'],
  'Tordillo': ['General Conesa','La Postrera'],
  'Tornquist': ['Tornquist','Chasicó','Pehuen-Co','Sierra de la Ventana','Saldungaray','Villa Ventana'],
  'Trenque Lauquen': ['Trenque Lauquen','30 de Agosto','Girodías','La Zanja','Moctezuma','Nueva Plata','Tronge'],
  'Tres Arroyos': ['Tres Arroyos','Claromecó','Copetonas','De la Garma','González Moreno','Irene','Micaela Cascallares','Orense','San Francisco de Bellocq'],
  'Tres de Febrero': ['Caseros','Ciudadela','El Palomar','Pablo Podestá','Santos Lugares','Villa Bosch','Villa del Parque','Villa Raffo'],
  'Tres Lomas': ['Tres Lomas','Algarrobo'],
  'Veinticinco de Mayo': ['Veinticinco de Mayo','Del Valle','Ernestina','Gobernador Ugarte','La Invernada','Norberto de la Riestra','Roberto Cano','Valdés'],
  'Vicente López': ['Vicente López','Carapachay','Florida','Munro','Olivos','Villa Adelina','Villa Martelli'],
  'Villa Gesell': ['Villa Gesell','Mar de las Pampas','Las Gaviotas','Mar Azul'],
  'Villarino': ['Médanos','Hilario Ascasubi','Mayor Buratovich','Teniente Origone','Pedro Luro'],
  'Zárate': ['Zárate','Campana','Lima'],
};

